# Generated by Django 5.2.17 on 2026-09-15 05:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('drive_date', models.DateField(blank=True, help_text='Optional placement drive date', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='PUBLISHED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('drive_link', models.URLField(verbose_name='Question paper link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Study materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=255)),
                ('university_no', models.CharField(max_length=100, verbose_name='University Register No')),
                ('address', models.TextField()),
                ('age', models.PositiveSmallIntegerField()),
                ('department', models.CharField(max_length=100)),
                ('current_year', models.PositiveSmallIntegerField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('backlogs', models.PositiveSmallIntegerField(default=0)),
                ('passout_year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('java', models.BooleanField(default=False)),
                ('c', models.BooleanField(default=False)),
                ('python', models.BooleanField(default=False)),
                ('cplusplus', models.BooleanField(default=False, verbose_name='C++')),
                ('javascript', models.BooleanField(default=False)),
                ('csharp', models.BooleanField(default=False, verbose_name='C#')),
                ('php', models.BooleanField(default=False)),
                ('sql', models.BooleanField(default=False, verbose_name='SQL')),
                ('html', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='placements.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(choices=[('PENDING', 'Yet to Happen'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('gd', models.CharField(choices=[('PENDING', 'Yet to Happen'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Group Discussion')),
                ('technical_interview', models.CharField(choices=[('PENDING', 'Yet to Happen'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('hr_interview', models.CharField(choices=[('PENDING', 'Yet to Happen'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='placements.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_role', models.CharField(max_length=255)),
                ('package', models.DecimalField(blank=True, decimal_places=2, help_text='Package in LPA', max_digits=6, null=True)),
                ('placement_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_history', to='placements.studentprofile')),
            ],
            options={
                'verbose_name_plural': 'Placement history',
                'ordering': ['-placement_date'],
            },
        ),
    ]
