# Generated by Django 5.2.17 on 2026-10-05 09:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_clean_architecture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('GLOBAL', 'Everyone'), ('COLLEGE', 'Selected colleges'), ('DRIVE', 'Placement drive applicants'), ('STUDENT', 'Specific students')], default='GLOBAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='drive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='placement_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='placements.placementdrive'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_skill_name'),
        ),
    ]
